const h = require('./helpers');
const { test, before, beforeEach } = require('node:test');
const assert = require('node:assert/strict');

before(async () => {
  await h.resetDb();
});

beforeEach(async () => {
  await h.resetDb();
});

const FAKE_SUMMARY = 'This is a test summary generated by the fake AI client.';

test('GET /api/books/:id/summary returns a summary (via fake AI client)', async () => {
  const user = await h.createUser();
  const book = await h.createBook({ title: 'The Hobbit', description: 'A hobbit adventure.' });

  const res = await h.api.get(`/api/books/${book.id}/summary`).set(h.auth(user));
  assert.equal(res.status, 200);
  assert.equal(res.body.summary.summary, FAKE_SUMMARY);
  assert.equal(res.body.summary.summaryType, 'SHORT');
  assert.equal(res.body.summary.sourceType, 'METADATA');
  assert.equal(res.body.summary.model, 'gpt-4o-mini');
});

test('summaries are cached: repeated requests do not generate new rows', async () => {
  const user = await h.createUser();
  const book = await h.createBook();

  await h.api.get(`/api/books/${book.id}/summary`).set(h.auth(user));
  const again = await h.api.get(`/api/books/${book.id}/summary`).set(h.auth(user));
  assert.equal(again.status, 200);
  assert.equal(again.body.summary.summary, FAKE_SUMMARY);

  const count = await h.prisma.bookSummary.count({ where: { bookId: book.id } });
  assert.equal(count, 1);
});

test('SHORT and DETAILED summaries are cached independently', async () => {
  const user = await h.createUser();
  const book = await h.createBook();

  await h.api.get(`/api/books/${book.id}/summary`).set(h.auth(user));
  await h.api.get(`/api/books/${book.id}/summary?type=DETAILED`).set(h.auth(user));

  const rows = await h.prisma.bookSummary.findMany({ where: { bookId: book.id } });
  assert.equal(rows.length, 2);
  assert.deepEqual(
    rows.map((r) => r.summaryType).sort(),
    ['DETAILED', 'SHORT'],
  );
});

test('GET /api/books/:id/summary returns 404 for a missing book', async () => {
  const user = await h.createUser();
  const res = await h.api.get('/api/books/missing/summary').set(h.auth(user));
  assert.equal(res.status, 404);
  assert.equal(res.body.error.code, 'BOOK_NOT_FOUND');
});
