const { test } = require('node:test');
const assert = require('node:assert/strict');
const {
  BookSummaryService,
  buildMetadataPrompt,
} = require('../../../src/services/ai/book-summary.service');
const { FakeAIClient } = require('../../../src/services/ai/fake-ai.client');

function makeBook(overrides = {}) {
  return {
    id: 'book_1',
    title: 'The Hobbit',
    description: 'A hobbit goes on an adventure.',
    publisher: 'George Allen & Unwin',
    publicationDate: new Date('1937-09-21'),
    language: 'en',
    authors: [{ author: { name: 'J. R. R. Tolkien' } }],
    categories: [{ category: { name: 'Fantasy' } }, { category: { name: 'Adventure' } }],
    ...overrides,
  };
}

function makeFakePrisma(book) {
  const store = {
    summaries: [],
  };

  return {
    store,
    bookSummary: {
      findUnique: async ({ where }) => {
        const { bookId, summaryType, sourceType } = where.bookId_summaryType_sourceType;
        return (
          store.summaries.find(
            (s) => s.bookId === bookId && s.summaryType === summaryType && s.sourceType === sourceType,
          ) || null
        );
      },
      create: async ({ data }) => {
        const row = { id: `summary_${store.summaries.length + 1}`, ...data };
        store.summaries.push(row);
        return row;
      },
    },
    book: {
      findUnique: async ({ where }) => (book && where.id === book.id ? book : null),
    },
  };
}

test('returns a cached summary without calling the AI client', async () => {
  const ai = new FakeAIClient();
  const prisma = makeFakePrisma(makeBook());
  const cached = {
    id: 's1',
    bookId: 'book_1',
    summary: 'Cached summary',
    summaryType: 'SHORT',
    sourceType: 'METADATA',
    model: 'fake-model',
  };
  prisma.store.summaries.push(cached);

  const service = new BookSummaryService(prisma, ai);
  const result = await service.getSummary('book_1', 'SHORT');

  assert.equal(result.summary, 'Cached summary');
  assert.equal(ai.calls, 0);
});

test('generates and persists a summary when nothing is cached', async () => {
  const ai = new FakeAIClient();
  const prisma = makeFakePrisma(makeBook());
  const service = new BookSummaryService(prisma, ai);

  const result = await service.getSummary('book_1', 'SHORT');

  assert.equal(result.summary, 'This is a test summary generated by the fake AI client.');
  assert.equal(result.summaryType, 'SHORT');
  assert.equal(result.sourceType, 'METADATA');
  assert.equal(ai.calls, 1);
  assert.equal(prisma.store.summaries.length, 1);

  // Second call hits the cache
  const again = await service.getSummary('book_1', 'SHORT');
  assert.equal(again.id, result.id);
  assert.equal(ai.calls, 1);
});

test('throws BOOK_NOT_FOUND for a missing book', async () => {
  const ai = new FakeAIClient();
  const prisma = makeFakePrisma(null);
  const service = new BookSummaryService(prisma, ai);

  await assert.rejects(
    () => service.getSummary('missing', 'SHORT'),
    (err) => err.code === 'BOOK_NOT_FOUND' && err.statusCode === 404,
  );
  assert.equal(ai.calls, 0);
});

test('buildMetadataPrompt includes title, authors and categories', () => {
  const prompt = buildMetadataPrompt(makeBook(), 'SHORT');
  assert.ok(prompt.includes('The Hobbit'));
  assert.ok(prompt.includes('J. R. R. Tolkien'));
  assert.ok(prompt.includes('Fantasy'));
  assert.ok(prompt.includes('Adventure'));
  assert.ok(prompt.includes('Write a short summary'));
});

test('buildMetadataPrompt produces a detailed instruction for DETAILED', () => {
  const prompt = buildMetadataPrompt(makeBook(), 'DETAILED');
  assert.ok(prompt.includes('Write a detailed'));
});
