/**
 * Deterministic fake AI client used in development and automated tests.
 * It never touches the real AI API, so it does not consume quota.
 */
class FakeAIClient {
  constructor({ model = 'fake-model' } = {}) {
    this.model = model;
    this.calls = 0;
  }

  async generateSummary(_prompt) {
    this.calls += 1;
    return 'This is a test summary generated by the fake AI client.';
  }
}

module.exports = { FakeAIClient };
